---
  - hosts: host1
    sudo: yes
    name: Play 1
    tasks:
    - name: Execute command "Date"
      command: date
    - script: test_script.sh

  # - hosts: host2
  #  name: Play 2
  # sudo: yes
  # tasks:
  #  - name: Execute Scipt on server
  #   script: test_script.sh
  #- name: Install Ngix
  # apt: name=ngix state=latest 
